name: 'Get mods'
description: 'Gets mod releases'
inputs:
  mod-db:
    description: 'JSON list of mods to check'
    required: true
    default: '[]'
  github-token:
    description: 'Token for GitHub authentication'
    required: true
outputs:
  releases:
    description: 'JSON list of latest mod releases'
runs:
  using: 'node12'
  main: 'build/index.js'
